GET http://localhost:8080/api/customers
Accept: application/json

###
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "name": "Teszt Aladár",
  "city": "Bp",
  "address": "asdfsd",
  "phoneNumber": "91123456",
  "email": "name@domain.hu"
}

###
PUT http://localhost:8080/api/customers/1
Content-Type: application/json

{
  "name": "asd",
  "city": "asd",
  "address": "",
  "phoneNumber": "91123456",
  "email": "name@domain.hu"
}

###
DELETE http://localhost:8080/api/customers/1
#Content-Type: application/json